INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = respringmyihelper

respringmyihelper_FILES = Tweak.x
respringmyihelper_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
